#!/usr/bin/env python3
#
# This file is part of the Robotic Observatory Control Kit (rockit)
#
# rockit is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# rockit is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with rockit.  If not, see <http://www.gnu.org/licenses/>.

"""Commandline client for controlling an ASA OK3Z Focuser"""

import glob
import json
import os
import sys
import Pyro4
from rockit.common import TFmt
from rockit.focuser.ok3z import Config, CommandStatus, FocuserStatus


SCRIPT_NAME = os.path.basename(sys.argv[0])
sys.excepthook = Pyro4.util.excepthook


def run_command(command, args):
    """Runs a daemon command, handling error messages"""
    if 'FOCUSD_CONFIG_PATH' in os.environ:
        config = Config(os.environ['FOCUSD_CONFIG_PATH'])
    else:
        # Load the config file defined in the FOCUSD_CONFIG_PATH environment variable or from the
        # default system location (/etc/focusd/). Exit with an error if zero or multiple are found.
        files = glob.glob("/etc/focusd/*.json")
        if len(files) != 1:
            print('error: failed to guess the default config file. ' +
                  'Run as FOCUSD_CONFIG_PATH=/path/to/config.json focus <command>')
            return 1

        config = Config(files[0])

    try:
        ret = command(config, args)
    except Pyro4.errors.CommunicationError:
        ret = -101

    # Print message associated with error codes, except for -1 (error handled locally)
    if ret not in [-1, 0]:
        print(CommandStatus.message(ret))
    sys.exit(ret)


def print_status(config, _):
    """Prints a human-readable summary of the focuser status"""
    with config.daemon.connect() as focusd:
        data = focusd.report_status()

    label = f'Focuser is {FocuserStatus.label(data["status"], True)}'
    if data['status'] == FocuserStatus.Idle:
        label += f' ({TFmt.Bold}{data["current_mm"]:.3f}{TFmt.Clear} mm)'
    elif data['status'] == FocuserStatus.Moving:
        label += f' ({TFmt.Bold}{data["current_mm"]:.3f}{TFmt.Clear} / '
        label += f'{TFmt.Bold}{data["target_mm"]:.3f}{TFmt.Clear} mm)'

    print(label)
    return 0


def print_json(config, _):
    """Prints a machine-readable summary of the focuser status"""
    with config.daemon.connect() as focusd:
        print(json.dumps(focusd.report_status() or {}))

    return 0


def set_position(config, args):
    """Request focuser to move a specific step position"""
    try:
        if len(args) == 1:
            position = float(args[0])
            try:
                with config.daemon.connect(timeout=0) as focusd:
                    return focusd.set_focus(position)
            except KeyboardInterrupt:
                # ctrl-c terminates the running command
                with config.daemon.connect() as focusd:
                    return focusd.stop()
    except ValueError:
        pass

    print(f'usage: {SCRIPT_NAME} set <mm position>')
    return -1


def offset_position(config, args):
    """Request focuser to move by a specific step delta"""
    try:
        if len(args) == 1:
            delta = float(args[0])

            try:
                with config.daemon.connect(timeout=0) as focusd:
                    return focusd.set_focus(delta, offset=True)
            except KeyboardInterrupt:
                # ctrl-c terminates the running command
                with config.daemon.connect() as focusd:
                    return focusd.stop()
    except ValueError:
        pass
    print(f'usage: {SCRIPT_NAME} offset <mm delta>')
    return -1


def initialize(config, _):
    """Connect to the focuser"""
    with config.daemon.connect(timeout=config.move_timeout + 5) as focusd:
        return focusd.initialize()


def shutdown(config, *_):
    """Disconnect from the focuser"""
    with config.daemon.connect() as focusd:
        return focusd.shutdown()


def print_usage():
    """Prints the utility help"""
    print(f'usage: {SCRIPT_NAME} <command> [<args>]')
    print()
    print('general commands:')
    print('   set          request the focuser to move to a given absolute position')
    print('   offset       request the focuser to move by a given offset delta')
    print('   status       print a human-readable summary of the focuser status')
    print('   json         print a machine-readable summary of the focuser status')
    print('engineering commands:')
    print('   init         connect to the focuser')
    print('   kill         disconnect from the focuser')
    print()

    return 0


if __name__ == '__main__':
    commands = {
        'set': set_position,
        'offset': offset_position,
        'status': print_status,
        'json': print_json,
        'init': initialize,
        'kill': shutdown,
    }

    if len(sys.argv) >= 2 and sys.argv[1] in commands:
        sys.exit(run_command(commands[sys.argv[1]], sys.argv[2:]))

    sys.exit(print_usage())
